### ISSUE TITLE
TItan Reputation Login Error 

### ISSUE THREAD

**Issue by Chzconey** [paulbuechner/titan-reputation#1]
Here is the error that I am getting upon login.

18x` TitanReputation/src/main.lua:1151: attempt to index global 'TitanRep_Data' (a nil value)
[string "@TitanReputation/src/main.lua"]:1151: in function `method'
[string "@TitanReputation/src/main.lua"]:1489: in function `TitanPanelReputation_GatherFactions'
[string "@TitanReputation/src/main.lua"]:234: in function `TitanPanelReputationButton_OnEvent'
[string "*main.xml:15_OnEvent"]:1: in function <[string "*main.xml:15_OnEvent"]:1>

Locals:
name = "Court of Harvesters"
parentName = "Shadowlands"
standingID = 8
topValue = 10000
earnedValue = 1695
percent = "16.95"
isHeader = false
isCollapsed = false
isInactive = false
hasRep = false
isChild = false
isFriendship = false
factionID = 2413
hasBonusRepGain = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'TitanRep_Data' (a nil value)"
TITANREP_TABLE_INIT = true
TITANREP_TABLE = <table> {
 2511 = <table> {
 }
 2526 = <table> {
 }
 2507 = <table> {
 }
 2510 = <table> {
 }
 2503 = <table> {
 }
 1168 = <table> {
 }
}
TITANREP_PARAGON = "Paragon"
MYBARCOLORS = <table> {
 7 = <table> {
 }
 1 = <table> {
 }
 2 = <table> {
 }
 4 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 5 = <table> {
 }
 10 = <table> {
 }
 3 = <table> {
 }
 6 = <table> {
 }
}

**Comment by paulbuechner** [comment]
Can u provide information on what version the issue appears?

**Comment by Chzconey** [comment]
V10.2.0.6 The newest Update

**Comment by paulbuechner** [comment]
I added a missing null check  635638c4a16f7f15f314af15e35e1c0a15a2f416, which might cause this issue. Please let me know if this resolves the issue.

Release: [v10.2.0.7](https://github.com/paulbuechner/titan-reputation/tree/v10.2.0.7)
